# Generated by Django 5.1.3 on 2024-11-27 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0003_subject_remove_teacher_subject_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='teachers', to='teachers.teacher')),
            ],
        ),
    ]
