# Generated by Django 5.1.3 on 2024-11-23 16:12

import apps.students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(null=True, upload_to=apps.students.models.generate_unique_name),
        ),
        migrations.AlterModelTable(
            name='parent',
            table='parents',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
