# Generated by Django 5.1.3 on 2024-11-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='father_mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_mobile',
            field=models.CharField(max_length=15),
        ),
    ]
