# Generated by Django 5.1.3 on 2024-11-25 23:04

import apps.students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_parent_father_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='permanent_address',
            field=models.TextField(verbose_name=20),
        ),
        migrations.AlterField(
            model_name='parent',
            name='present_address',
            field=models.TextField(verbose_name=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.students.models.generate_unique_name),
        ),
    ]
