# Generated by Django 5.1.3 on 2024-11-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_rename_permanent_address_parent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='description',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parent',
            name='father_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parent',
            name='father_mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='fee',
            table='fees',
        ),
    ]
