# Generated by Django 5.1.3 on 2024-11-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_fee_description_alter_fee_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_class',
            new_name='grade',
        ),
    ]
