# Generated by Django 5.1.3 on 2024-11-27 09:49

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_rename_student_class_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='father_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KE'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KE'),
        ),
    ]
