# Generated by Django 5.1.3 on 2024-11-27 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_parent_father_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='term_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.parent'),
        ),
    ]
