# Generated by Django 5.1.3 on 2024-11-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_class',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
